import type { DemodMode } from '../radio/passband';
import type { AgcMode, NoiseBlankerMode, NoiseReductionMode } from '../settings/types';

export type TciClientRole = 'operator' | 'viewer';

export type TciRadioState = {
  mode: DemodMode;
  vfoA: number;
  vfoB: number;
  dds: number;
  rxAdc: number;
  rxAntenna: number;
  sampleRate: number;
  audioSampleRate: number;
  rxVolumeDb: number;
  rxNoiseReductionMode: NoiseReductionMode;
  rxNoiseReductionLevel: number;
  rxNbMode: NoiseBlankerMode;
  rxNbThreshold: number;
  rxAnrTaps: number;
  rxAnrDelay: number;
  rxAnrGain: number;
  rxAnrLeakage: number;
  anfEnabled: boolean;
  rxAnfTaps: number;
  rxAnfDelay: number;
  rxAnfGain: number;
  rxAnfLeakage: number;
  agcMode: AgcMode;
  agcGain: number;
  filterLow: number;
  filterHigh: number;
  rxFilterShiftHz: number;
  txFilterLow: number;
  txFilterHigh: number;
  meterDbm: number | null;
  txPower: number | null;
  swr: number | null;
  bridgeRttMs: number | null;
  bridgeRttAt: number;
  backpressureSafetyP50Us: number;
  backpressureSafetyP95Us: number;
  backpressureSafetyP99Us: number;
  backpressureControlP50Us: number;
  backpressureControlP95Us: number;
  backpressureControlP99Us: number;
  displayReplacedPerSec: number;
  displayDroppedPerSec: number;
  bridgeAudioDroppedPerSec: number;
  bridgeAudioSeqGapCount: number;
  audioSeqGapCount: number;
  audioPanicDrainCount: number;
  sendBlockedMs: number;
  outboundHighWatermarkBytes: number;
  safetyQueueDepthOverflowCount: number;
  txFaultReason: string | null;
  remoteClientRole: TciClientRole | null;
  remoteClientId: string | null;
  txDrive: number;
  remoteTxRfEnabled: boolean | null;
  txEnabled: boolean;
  moxRequested: boolean;
  txPhase: 'rx' | 'armed' | 'keyed';
  audioStreaming: boolean;
  rxEqEnabled: boolean;
  txEqEnabled: boolean;
  rxEqBands: number[];
  txEqBands: number[];
  cfcEnabled: boolean;
  cfcPrecomp: number;
  cfcBands: number[];
  twoToneEnabled: boolean;
  txTwoToneFreq1: number;
  txTwoToneFreq2: number;
  txTwoToneLevelDb: number;
  txTwoToneInvertLsb: boolean;
  txTwoToneDelayMs: number;
  txNoiseGateEnabled: boolean;
  txNoiseGateThresholdDb: number;
};

export type TciApplyResult = {
  state: TciRadioState;
  ready: boolean;
  displayCenterHzChanged: boolean;
  sampleRateChanged: boolean;
  rxVolumeChanged: boolean;
  txReleased: boolean;
  txFault: string | null;
};
