import type { DemodMode } from '../radio/passband';
import type {
  AgcMode,
  NoiseBlankerMode,
  NoiseReductionMode,
  Nr2GainMethod,
  Nr2NpeMethod,
  WbfmDeemphasis,
} from '../settings/types';

export type TciClientRole = 'operator' | 'viewer';
export type TxCodecName = 'pcm' | 'opus_nb' | 'opus_wb';

export type TciRadioState = {
  mode: DemodMode;
  vfoA: number;
  vfoB: number;
  dds: number;
  rxAdc: number;
  rxAntenna: number;
  sampleRate: number;
  audioSampleRate: number;
  rxVolumeDb: number;
  rxNoiseReductionMode: NoiseReductionMode;
  rxNoiseReductionLevel: number;
  rxNr2GainMethod: Nr2GainMethod;
  rxNr2NpeMethod: Nr2NpeMethod;
  rxNr2PostFilterEnabled: boolean;
  rxWbfmSupported: boolean;
  rxWbfmDeemphasis: WbfmDeemphasis;
  rxWbfmStereoDetected: boolean;
  rxNbMode: NoiseBlankerMode;
  rxNbThreshold: number;
  rxAnrTaps: number;
  rxAnrDelay: number;
  rxAnrGain: number;
  rxAnrLeakage: number;
  anfEnabled: boolean;
  rxAnfTaps: number;
  rxAnfDelay: number;
  rxAnfGain: number;
  rxAnfLeakage: number;
  agcMode: AgcMode;
  agcGain: number;
  filterLow: number;
  filterHigh: number;
  rxFilterShiftHz: number;
  txFilterLow: number;
  txFilterHigh: number;
  meterDbm: number | null;
  txPower: number | null;
  swr: number | null;
  bridgeRttMs: number | null;
  bridgeRttAt: number;
  backpressureSafetyP50Us: number;
  backpressureSafetyP95Us: number;
  backpressureSafetyP99Us: number;
  backpressureControlP50Us: number;
  backpressureControlP95Us: number;
  backpressureControlP99Us: number;
  displayReplacedPerSec: number;
  displayDroppedPerSec: number;
  bridgeAudioDroppedPerSec: number;
  bridgeAudioSeqGapCount: number;
  audioSeqGapCount: number;
  audioPanicDrainCount: number;
  sendBlockedMs: number;
  outboundHighWatermarkBytes: number;
  safetyQueueDepthOverflowCount: number;
  txUplinkDegraded: boolean;
  txMicDroppedCount: number;
  txUplinkBufferedBytes: number;
  txUplinkBufferedHwmBytes: number;
  txMicLastArrivedSeq: number;
  txMicSeqGapCount: number;
  txMicAgeMs: number;
  txFaultReason: string | null;
  txCodecDecodeErrorCount: number;
  txCodecStaleDropCount: number;
  txCodecReleaseFlushCount: number;
  txCodecRequested: TxCodecName;
  txCodecAccepted: TxCodecName | null;
  txCodecNegotiatedAt: number;
  txCodecRejectReason: string | null;
  remoteClientRole: TciClientRole | null;
  remoteClientId: string | null;
  txDrive: number;
  remoteTxRfEnabled: boolean | null;
  txEnabled: boolean;
  moxRequested: boolean;
  txPhase: 'rx' | 'armed' | 'keyed';
  audioStreaming: boolean;
  rxEqEnabled: boolean;
  txEqEnabled: boolean;
  rxEqBands: number[];
  txEqBands: number[];
  cfcEnabled: boolean;
  cfcPrecomp: number;
  cfcBands: number[];
  txPhaseRotatorEnabled: boolean;
  txPhaseRotatorAuto: boolean;
  txPhaseRotatorCornerHz: number;
  pureSignalEnabled: boolean;
  pureSignalAutoAttenuate: boolean;
  pureSignalAttenuationDb: number;
  pureSignalState: 'off' | 'waiting' | 'calibrating' | 'correcting' | 'fault';
  pureSignalFeedbackLevel: number;
  pureSignalCalibrationCount: number;
  pureSignalCorrecting: boolean;
  pureSignalMaxTx: number;
  pureSignalFeedbackPackets: number;
  pureSignalFeedbackGaps: number;
  twoToneEnabled: boolean;
  txTwoToneFreq1: number;
  txTwoToneFreq2: number;
  txTwoToneLevelDb: number;
  txTwoToneInvertLsb: boolean;
  txTwoToneDelayMs: number;
  txNoiseGateEnabled: boolean;
  txNoiseGateThresholdDb: number;
};

export type TciApplyResult = {
  state: TciRadioState;
  ready: boolean;
  displayCenterHzChanged: boolean;
  sampleRateChanged: boolean;
  rxVolumeChanged: boolean;
  txReleased: boolean;
  txFault: string | null;
};
