PACKAGE_NAME="saturn-xdma"
PACKAGE_VERSION="2020.1.8-saturn"

BUILT_MODULE_NAME[0]="xdma"
BUILT_MODULE_LOCATION[0]="xdma"
DEST_MODULE_LOCATION[0]="/updates/dkms"

MAKE[0]="make -C xdma KDIR=/lib/modules/${kernelver}/build"
CLEAN="make -C xdma KDIR=/lib/modules/${kernelver}/build clean"

AUTOINSTALL="yes"
