import { createRemoteController } from './controller/create-controller';
import { createRemoteSession } from './runtime/session';
import { createDefaultSettingsState } from './settings/defaults';
import {
  applyRemoteSettingsToState,
  normalizeRemoteSettings,
  settingsStateToRemoteSettings,
  normalizeBandMemory,
  clampSampleRateHz,
  clampRxAdc,
  clampRxAntenna,
  clampRxVolumeDb,
  normalizeNrMode,
  clampRxNoiseReductionLevel,
  normalizeNbMode,
  clampRxNbThreshold,
  normalizeAgcMode,
  clampAgcGain,
  clampDspTapCount,
  clampDspDelay,
  clampDspGain,
  clampDspLeakage,
  clampTxDriveWatts,
  clampTxMicGainDb,
  normalizeTxMeterMode,
  clampTwoToneFreqHz,
  clampTwoToneLevelDb,
  clampTwoToneDelayMs,
  clampEqGainDb,
  sanitizeEqBands,
  sanitizeCfcBands,
  clampDisplayDb,
  clampSpectrumAverage,
  clampWaterfallSpeed,
  normalizeWaterfallPalette,
  sanitizePhonePanels,
  normalizeRadioPrefs,
  normalizeDisplayPrefs,
} from './settings/normalize';
import { parseTciText } from './tci/parser';
import { applyTciText } from './tci/apply';
import { classifyFrame, decodeRxFrame, decodeIqFrame, decodeAudioFrame } from './transport/rx-frame';
import { parseTciBinaryFrameHeader } from './transport/tci-frame';
import { applyIqFrame, applyAudioFrame, fftSizeForSamples, buildRenderIqWindow } from './transport/rx-apply';
import {
  buildTxMicPcmS16Frame,
  decideTxMicSend,
  detectTxCodecCapabilities,
  txMicByteRateBytesPerSecond,
  txUplinkBufferedThresholdBytes,
  txUplinkHardCapBytesForCodec,
  TX_MIC_BYTES_PER_SAMPLE_S16,
  TX_MIC_CODEC_PCM,
  TX_MIC_CODEC_OPUS_NB,
  TX_MIC_CODEC_OPUS_WB,
  TX_MIC_FRAME_HEADER_BYTES,
  TX_MIC_SAMPLE_RATE_HZ,
  TX_MIC_SAMPLE_TYPE_S16,
  TX_MIC_STREAM_TYPE,
} from './transport/tx-uplink';
import {
  PHASE42_CONTROL_PATH,
  PHASE42_MEDIA_PATH,
  PHASE42_SOCKET_OPEN,
  buildPhase42SessionOpenMessage,
  createPhase42SplitSocketClient,
  derivePhase42SplitSocketUrls,
  decidePhase42MediaSend,
  PHASE42_MEDIA_BACKLOG_HARD_CAP_BYTES,
} from './transport/split-sockets';
import { createPhase42LegacySocketAdapter } from './transport/phase42-adapter';
import {
  PHASE42_SPLIT_QUERY_PARAM,
  PHASE42_SPLIT_STORAGE_KEY,
  createPhase42SessionId,
  phase42SplitTransportEnabled,
} from './transport/transport-mode';
import { bandKeyForFrequency, effectiveIqSampleRate, HAM_BAND_EDGES_HZ, adcLabel, antennaLabel, normalizeStreamMode, noiseReductionLabel, describeMicCaptureError } from './radio/band';
import {
  normalizeDemodMode,
  clampDemodMode,
  isNegativePassbandMode,
  isSymmetricPassbandMode,
  clampFilterLowHz,
  clampFilterHighHz,
  signedPassbandFromUiCuts,
  shiftedSignedPassbandFromUiCuts,
  decomposeSignedPassbandWithShift,
  defaultSignedRxPassbandForMode,
  defaultSignedTxPassbandForMode,
  defaultFilterCutsForMode,
  uiCutsFromSignedPassband,
  clickTuneCarrierOffsetHz,
  DEMOD_MODES,
} from './radio/passband';
import { formatFrequencyHz, formatFrequencyMarkup, clampFrequencyHz, snapTuneFrequencyHz, formatFrequencyPlain, safeFiniteNumber, safeFixed } from './radio/frequency';
import { anrPreset, anfPreset } from './radio/dsp-presets';
import {
  buildRxFilterBandCommand,
  buildTxFilterBandCommand,
  buildAnrCommands,
  buildAnfCommands,
  buildTwoToneCommands,
  buildAllRadioPrefsCommands,
  buildTxCodecCapsCommand,
} from './tci/commands';
import { resampleChannel, prepareAudioForPlayback, ringBufferFreeFrames } from './audio/resample';
import * as AudioConstants from './audio/constants';
import { volumeAmplitudeFromDb } from './audio/constants';
import { FftProcessor } from './dsp/fft';
import {
  lerp, moveToward, svgArcPath, dbmToSmDeg, auxDeg, txPowerToAuxDeg, swrToAuxDeg,
  SM_CX, SM_CY, SM_R, SM_START, SM_END, SM_S9_DEG,
  AX_CX, AX_CY, AX_R, AX_START, AX_END, AX_SPAN,
  SMETER_ATTACK_PER_SEC, SMETER_RELEASE_PER_SEC, SMETER_PEAK_HOLD_MS, SMETER_PEAK_DROP_PER_SEC,
  TX_POWER_ATTACK_PER_SEC, TX_POWER_RELEASE_PER_SEC, TX_POWER_PEAK_HOLD_MS, TX_POWER_PEAK_DROP_PER_SEC,
  SWR_ATTACK_PER_SEC, SWR_RELEASE_PER_SEC,
} from './ui/meter-math';
import {
  displaySpanHz,
  displayPercentForOffsetHz,
  visibleBinsForDisplay,
  shiftBinsHorizontally,
  bandEdgesInView,
  autoRangeFromBins,
} from './dsp/display';
import { createAppState, PHONE_PANEL_DEFAULTS } from './state/app-state';
import type { AppState, PhonePanels } from './state/app-state';
import { radioPrefsFromState, displayPrefsFromState } from './state/prefs-from-state';
import { buildPerfSnapshot, buildPerfSummary } from './state/perf-snapshot';
import { applyRadioPrefsToState, applyDisplayPrefsToState, normalizeAppStateInPlace } from './state/apply-prefs';

const api = {
  // Controller / runtime
  createRemoteController,
  createRemoteSession,
  createDefaultSettingsState,
  applyRemoteSettingsToState,
  normalizeRemoteSettings,
  settingsStateToRemoteSettings,

  // TCI parsing
  parseTciText,
  applyTciText,

  // TCI command builders
  buildRxFilterBandCommand,
  buildTxFilterBandCommand,
  buildAnrCommands,
  buildAnfCommands,
  buildTwoToneCommands,
  buildAllRadioPrefsCommands,
  buildTxCodecCapsCommand,

  // Transport
  decodeRxFrame,
  classifyFrame,
  decodeIqFrame,
  decodeAudioFrame,
  parseTciBinaryFrameHeader,
  applyIqFrame,
  applyAudioFrame,
  fftSizeForSamples,
  buildRenderIqWindow,
  buildTxMicPcmS16Frame,
  decideTxMicSend,
  detectTxCodecCapabilities,
  txMicByteRateBytesPerSecond,
  txUplinkBufferedThresholdBytes,
  TX_MIC_BYTES_PER_SAMPLE_S16,
  TX_MIC_CODEC_PCM,
  TX_MIC_CODEC_OPUS_NB,
  TX_MIC_CODEC_OPUS_WB,
  TX_MIC_FRAME_HEADER_BYTES,
  TX_MIC_SAMPLE_RATE_HZ,
  TX_MIC_SAMPLE_TYPE_S16,
  TX_MIC_STREAM_TYPE,
  PHASE42_CONTROL_PATH,
  PHASE42_MEDIA_PATH,
  PHASE42_SOCKET_OPEN,
  buildPhase42SessionOpenMessage,
  createPhase42SplitSocketClient,
  derivePhase42SplitSocketUrls,
  decidePhase42MediaSend,
  PHASE42_MEDIA_BACKLOG_HARD_CAP_BYTES,
  createPhase42LegacySocketAdapter,
  PHASE42_SPLIT_QUERY_PARAM,
  PHASE42_SPLIT_STORAGE_KEY,
  createPhase42SessionId,
  phase42SplitTransportEnabled,

  // Radio
  bandKeyForFrequency,
  effectiveIqSampleRate,
  HAM_BAND_EDGES_HZ,
  DEMOD_MODES,
  adcLabel,
  antennaLabel,
  normalizeStreamMode,
  noiseReductionLabel,
  describeMicCaptureError,
  normalizeDemodMode,
  clampDemodMode,
  isNegativePassbandMode,
  isSymmetricPassbandMode,
  clampFilterLowHz,
  clampFilterHighHz,
  signedPassbandFromUiCuts,
  shiftedSignedPassbandFromUiCuts,
  decomposeSignedPassbandWithShift,
  uiCutsFromSignedPassband,
  clickTuneCarrierOffsetHz,
  defaultSignedRxPassbandForMode,
  defaultSignedTxPassbandForMode,
  defaultFilterCutsForMode,
  formatFrequencyHz,
  formatFrequencyMarkup,
  formatFrequencyPlain,
  clampFrequencyHz,
  snapTuneFrequencyHz,
  safeFiniteNumber,
  safeFixed,
  anrPreset,
  anfPreset,

  // Settings clamp/normalize
  clampSampleRateHz,
  clampRxAdc,
  clampRxAntenna,
  clampRxVolumeDb,
  normalizeNrMode,
  clampRxNoiseReductionLevel,
  normalizeNbMode,
  clampRxNbThreshold,
  normalizeAgcMode,
  clampAgcGain,
  clampDspTapCount,
  clampDspDelay,
  clampDspGain,
  clampDspLeakage,
  clampTxDriveWatts,
  clampTxMicGainDb,
  normalizeTxMeterMode,
  clampTwoToneFreqHz,
  clampTwoToneLevelDb,
  clampTwoToneDelayMs,
  clampEqGainDb,
  sanitizeEqBands,
  sanitizeCfcBands,
  clampDisplayDb,
  clampSpectrumAverage,
  clampWaterfallSpeed,
  normalizeWaterfallPalette,
  sanitizePhonePanels,
  normalizeRadioPrefs,
  normalizeDisplayPrefs,
  normalizeBandMemory,

  // Audio
  volumeAmplitudeFromDb,
  resampleChannel,
  prepareAudioForPlayback,
  ringBufferFreeFrames,
  AudioConstants,

  // DSP
  FftProcessor,
  displaySpanHz,
  displayPercentForOffsetHz,
  visibleBinsForDisplay,
  shiftBinsHorizontally,
  bandEdgesInView,
  autoRangeFromBins,

  // State
  createAppState,
  PHONE_PANEL_DEFAULTS,
  radioPrefsFromState,
  displayPrefsFromState,
  buildPerfSnapshot,
  buildPerfSummary,
  applyRadioPrefsToState,
  applyDisplayPrefsToState,
  normalizeAppStateInPlace,

  // Meter math
  lerp, moveToward, svgArcPath, dbmToSmDeg, auxDeg, txPowerToAuxDeg, swrToAuxDeg,
  SM_CX, SM_CY, SM_R, SM_START, SM_END, SM_S9_DEG,
  AX_CX, AX_CY, AX_R, AX_START, AX_END, AX_SPAN,
  SMETER_ATTACK_PER_SEC, SMETER_RELEASE_PER_SEC, SMETER_PEAK_HOLD_MS, SMETER_PEAK_DROP_PER_SEC,
  TX_POWER_ATTACK_PER_SEC, TX_POWER_RELEASE_PER_SEC, TX_POWER_PEAK_HOLD_MS, TX_POWER_PEAK_DROP_PER_SEC,
  SWR_ATTACK_PER_SEC, SWR_RELEASE_PER_SEC,
};

export type { AppState, PhonePanels };

export const SaturnRemoteNext = api;

(globalThis as typeof globalThis & { SaturnRemoteNext?: typeof api }).SaturnRemoteNext = api;

export {
  createRemoteController,
  createRemoteSession,
  createDefaultSettingsState,
  applyRemoteSettingsToState,
  normalizeRemoteSettings,
  settingsStateToRemoteSettings,
  parseTciText,
  applyTciText,
  buildRxFilterBandCommand,
  buildTxFilterBandCommand,
  buildAnrCommands,
  buildAnfCommands,
  buildTwoToneCommands,
  buildAllRadioPrefsCommands,
  decodeRxFrame,
  classifyFrame,
  decodeIqFrame,
  decodeAudioFrame,
  parseTciBinaryFrameHeader,
  applyIqFrame,
  applyAudioFrame,
  fftSizeForSamples,
  buildRenderIqWindow,
  buildTxMicPcmS16Frame,
  decideTxMicSend,
  txMicByteRateBytesPerSecond,
  txUplinkBufferedThresholdBytes,
  txUplinkHardCapBytesForCodec,
  TX_MIC_BYTES_PER_SAMPLE_S16,
  TX_MIC_CODEC_PCM,
  TX_MIC_FRAME_HEADER_BYTES,
  TX_MIC_SAMPLE_RATE_HZ,
  TX_MIC_SAMPLE_TYPE_S16,
  TX_MIC_STREAM_TYPE,
  PHASE42_CONTROL_PATH,
  PHASE42_MEDIA_PATH,
  PHASE42_SOCKET_OPEN,
  buildPhase42SessionOpenMessage,
  createPhase42SplitSocketClient,
  derivePhase42SplitSocketUrls,
  decidePhase42MediaSend,
  PHASE42_MEDIA_BACKLOG_HARD_CAP_BYTES,
  createPhase42LegacySocketAdapter,
  PHASE42_SPLIT_QUERY_PARAM,
  PHASE42_SPLIT_STORAGE_KEY,
  createPhase42SessionId,
  phase42SplitTransportEnabled,
  bandKeyForFrequency,
  effectiveIqSampleRate,
  HAM_BAND_EDGES_HZ,
  DEMOD_MODES,
  adcLabel,
  antennaLabel,
  normalizeStreamMode,
  noiseReductionLabel,
  describeMicCaptureError,
  normalizeDemodMode,
  clampDemodMode,
  isNegativePassbandMode,
  isSymmetricPassbandMode,
  clampFilterLowHz,
  clampFilterHighHz,
  signedPassbandFromUiCuts,
  shiftedSignedPassbandFromUiCuts,
  decomposeSignedPassbandWithShift,
  uiCutsFromSignedPassband,
  clickTuneCarrierOffsetHz,
  defaultSignedRxPassbandForMode,
  defaultSignedTxPassbandForMode,
  defaultFilterCutsForMode,
  formatFrequencyHz,
  formatFrequencyMarkup,
  formatFrequencyPlain,
  clampFrequencyHz,
  snapTuneFrequencyHz,
  safeFiniteNumber,
  safeFixed,
  anrPreset,
  anfPreset,
  clampSampleRateHz,
  clampRxAdc,
  clampRxAntenna,
  clampRxVolumeDb,
  normalizeNrMode,
  clampRxNoiseReductionLevel,
  normalizeNbMode,
  clampRxNbThreshold,
  normalizeAgcMode,
  clampAgcGain,
  clampDspTapCount,
  clampDspDelay,
  clampDspGain,
  clampDspLeakage,
  clampTxDriveWatts,
  clampTxMicGainDb,
  normalizeTxMeterMode,
  clampTwoToneFreqHz,
  clampTwoToneLevelDb,
  clampTwoToneDelayMs,
  clampEqGainDb,
  sanitizeEqBands,
  sanitizeCfcBands,
  clampDisplayDb,
  clampSpectrumAverage,
  clampWaterfallSpeed,
  normalizeWaterfallPalette,
  sanitizePhonePanels,
  normalizeRadioPrefs,
  normalizeDisplayPrefs,
  normalizeBandMemory,
  volumeAmplitudeFromDb,
  resampleChannel,
  prepareAudioForPlayback,
  ringBufferFreeFrames,
  AudioConstants,
  FftProcessor,
  displaySpanHz,
  displayPercentForOffsetHz,
  visibleBinsForDisplay,
  shiftBinsHorizontally,
  bandEdgesInView,
  autoRangeFromBins,
  lerp, moveToward, svgArcPath, dbmToSmDeg, auxDeg, txPowerToAuxDeg, swrToAuxDeg,
  SM_CX, SM_CY, SM_R, SM_START, SM_END, SM_S9_DEG,
  AX_CX, AX_CY, AX_R, AX_START, AX_END, AX_SPAN,
  SMETER_ATTACK_PER_SEC, SMETER_RELEASE_PER_SEC, SMETER_PEAK_HOLD_MS, SMETER_PEAK_DROP_PER_SEC,
  TX_POWER_ATTACK_PER_SEC, TX_POWER_RELEASE_PER_SEC, TX_POWER_PEAK_HOLD_MS, TX_POWER_PEAK_DROP_PER_SEC,
  SWR_ATTACK_PER_SEC, SWR_RELEASE_PER_SEC,
  createAppState,
  PHONE_PANEL_DEFAULTS,
  radioPrefsFromState,
  displayPrefsFromState,
  buildPerfSnapshot,
  buildPerfSummary,
  applyRadioPrefsToState,
  applyDisplayPrefsToState,
  normalizeAppStateInPlace,
};
