import type { DisplayPrefs, PhonePanels, RadioPrefs, SettingsState } from './types';

export const DEFAULT_PHONE_PANELS: PhonePanels = {
  radio: false,
  dsp: true,
  tx: true,
  meters: false,
  setup: true,
  logs: true,
};

export const DEFAULT_RADIO_PREFS: RadioPrefs = {
  sampleRate: 192000,
  rxAdc: 0,
  rxAntenna: 1,
  mode: 'USB',
  rxVolumeDb: -10,
  rxNoiseReductionMode: 'OFF',
  rxNoiseReductionLevel: 0,
  rxNbMode: 'OFF',
  rxNbThreshold: 4.95,
  rxAnrTaps: 64,
  rxAnrDelay: 16,
  rxAnrGain: 0.0002,
  rxAnrLeakage: 0.00005,
  anfEnabled: false,
  rxAnfTaps: 64,
  rxAnfDelay: 16,
  rxAnfGain: 0.00012,
  rxAnfLeakage: 0.00008,
  agcMode: 'MEDIUM',
  agcGain: 80,
  filterLow: 50,
  filterHigh: 3050,
  txDrive: 10,
  txMicGainDb: -6,
  txFilterLow: 50,
  txFilterHigh: 3050,
  rxEqEnabled: false,
  rxEqBands: new Array(11).fill(0),
  txEqEnabled: false,
  txEqBands: new Array(11).fill(0),
  cfcEnabled: false,
  cfcPrecomp: 0,
  cfcBands: new Array(11).fill(0),
  txMeterMode: 'peak',
  twoToneEnabled: false,
  txTwoToneFreq1: 700,
  txTwoToneFreq2: 1900,
  txTwoToneLevelDb: 0,
  txTwoToneInvertLsb: true,
  txTwoToneDelayMs: 0,
  txNoiseGateEnabled: true,
  txNoiseGateThresholdDb: -30,
  txTimeoutEnabled: true,
  txTimeoutSeconds: 180,
};

export const DEFAULT_DISPLAY_PREFS: DisplayPrefs = {
  spectrumAutoRange: true,
  spectrumFloorDb: -200,
  spectrumCeilingDb: -120,
  waterfallAutoRange: true,
  waterfallFloorDb: -200,
  waterfallCeilingDb: -120,
  spectrumAverage: 1,
  waterfallSpeed: 1,
  waterfallPalette: 'classic',
  spectrumPeakHold: false,
  showGrid: true,
  showCenterLine: true,
  showBandEdges: true,
};

export function createDefaultSettingsState(): SettingsState {
  return {
    wsUrl: '',
    displayZoom: 1,
    frequencyLock: false,
    keepScreenAwake: false,
    streamMode: 'lan',
    layoutMode: 'desktop',
    theme: 'dark',
    phonePanels: { ...DEFAULT_PHONE_PANELS },
    activeProfile: '',
    radioPrefs: {
      ...DEFAULT_RADIO_PREFS,
      rxEqBands: DEFAULT_RADIO_PREFS.rxEqBands.slice(),
      txEqBands: DEFAULT_RADIO_PREFS.txEqBands.slice(),
      cfcBands: DEFAULT_RADIO_PREFS.cfcBands.slice(),
    },
    displayPrefs: { ...DEFAULT_DISPLAY_PREFS },
    bandMemory: {},
  };
}
