/**
 * Settings registry: the complete, searchable index of the console.
 *
 * Build-sheet rule (§8.11): Settings is the full index of the app, and the main
 * screen is a curated subset. This registry is the machine-readable form of that
 * index, so a parity audit can compare the discovered control inventory against
 * it instead of against prose.
 *
 * Conventions:
 * - `targetId` is the element id (or query-parameter / storage-key name) that the
 *   entry points at. For DOM kinds the id must exist in the template; the test
 *   suite enforces that.
 * - `synonyms` carries the pre-redesign names ("MON", "SQL", "ATT", "SATP") so a
 *   search for the old label still finds the control, per §8.11.
 * - `parityStatus` is deliberately honest: `wired` means the control exists and
 *   works today, `pending-integration` means it is reachable only through the
 *   legacy setup shell until Phase 3 wires the new surface.
 */

export type SettingsSectionId =
  | 'display'
  | 'meter'
  | 'receive'
  | 'transmit'
  | 'radio'
  | 'audio'
  | 'network'
  | 'memory'
  | 'log'
  | 'interface'
  | 'about';

export type SettingsTargetKind =
  | 'control'
  | 'readout'
  | 'toggle'
  | 'select'
  | 'slider'
  | 'button'
  | 'indicator'
  | 'overlay'
  | 'query-param'
  | 'storage-key';

export type SettingsParityStatus = 'wired' | 'pending-integration' | 'not-yet';

export type SettingsEntry = {
  id: string;
  section: SettingsSectionId;
  label: string;
  description: string;
  synonyms: string[];
  targetId: string;
  targetKind: SettingsTargetKind;
  mainScreen: 'always' | 'optional' | 'settings-only';
  safetyPinned?: boolean;
  parityStatus: SettingsParityStatus;
  /** For safety-critical controls: text that must appear in or beside the target
   *  element, so an id that exists but points at the wrong control fails. */
  domTextToken?: string;
  /** Legacy setup-sheet panel that already hosts this control, if any. */
  existingSetupPanel?: 'profiles' | 'display' | 'dsp' | 'tx' | 'network' | 'audio' | 'advanced';
  /** Extra element ids this entry also drives (per-tier duplicates, quick actions). */
  sourceControlIds?: string[];
};

export type SettingsSection = {
  id: SettingsSectionId;
  label: string;
  description: string;
  /** Live radio state lives here, so these sections must not offer "restore defaults". */
  affectsRadio?: boolean;
};

export const SETTINGS_SECTIONS: readonly SettingsSection[] = [
  { id: 'display', label: 'Display', description: 'Spectrum, waterfall and 3D view behaviour' },
  { id: 'meter', label: 'Meter', description: 'S-meter, TX meters and meter details' },
  { id: 'receive', label: 'Receive', description: 'RX audio, DSP and filtering', affectsRadio: true },
  { id: 'transmit', label: 'Transmit', description: 'TX audio path, monitor and transmit controls', affectsRadio: true },
  { id: 'radio', label: 'Radio', description: 'Radio path, band, mode and memories', affectsRadio: true },
  { id: 'audio', label: 'Audio', description: 'Devices, codec and audio health' },
  { id: 'network', label: 'Network', description: 'Bridge connection and transport' },
  { id: 'memory', label: 'Memory', description: 'Band memories' },
  { id: 'log', label: 'Log', description: 'Operator log and live client trace' },
  { id: 'interface', label: 'Interface', description: 'Theme, layout and keyboard' },
  { id: 'about', label: 'About and system', description: 'Device, versions, diagnostics' },
];

const entry = (value: SettingsEntry): SettingsEntry => value;

export const SETTINGS_REGISTRY: readonly SettingsEntry[] = [
  // ---- Shell entry points (build sheet §8.1, §8.9, §8.11) ----
  entry({ id: 'shell.settings', section: 'interface', label: 'Settings', description: 'Open the full settings index; gear button in the app bar.', synonyms: ['settings', 'gear', 'setup'], targetId: 'header-setup-btn', targetKind: 'button', mainScreen: 'always', safetyPinned: true, parityStatus: 'wired' }),
  entry({ id: 'shell.operationsDrawer', section: 'interface', label: 'Operations drawer', description: 'The Memory, Audio, Network, DSP, Radio and Log drawer.', synonyms: ['operations'], targetId: 'operations-drawer', targetKind: 'overlay', mainScreen: 'always', parityStatus: 'wired' }),
  entry({ id: 'memory.operationsTab', section: 'memory', label: 'Memory panel', description: 'Operations panel holding band memories.', synonyms: ['memory', 'operations'], targetId: 'operations-tab-memory', targetKind: 'button', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'audio.operationsTab', section: 'audio', label: 'Audio panel', description: 'Operations panel for the audio scope and levels.', synonyms: ['audio', 'operations'], targetId: 'operations-tab-audio', targetKind: 'button', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'network.operationsTab', section: 'network', label: 'Network panel', description: 'Operations panel for connection and transport detail.', synonyms: ['network', 'operations'], targetId: 'operations-tab-network', targetKind: 'button', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'receive.dspTab', section: 'receive', label: 'DSP panel', description: 'Operations panel for DSP detail.', synonyms: ['dsp', 'operations'], targetId: 'operations-tab-dsp', targetKind: 'button', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'radio.operationsTab', section: 'radio', label: 'Radio panel', description: 'Operations panel for radio path detail.', synonyms: ['radio', 'operations'], targetId: 'operations-tab-radio', targetKind: 'button', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'radio.keypad', section: 'radio', label: 'Direct frequency entry', description: 'Type a frequency on the on-screen keypad.', synonyms: ['keypad', 'entry', 'direct entry'], targetId: 'freq-entry-overlay', targetKind: 'overlay', mainScreen: 'always', parityStatus: 'wired' }),

  // ---- Display (build sheet §8.5, §11) ----
  entry({ id: 'display.view', section: 'display', label: 'Display view', description: 'Choose the Hi-Res 3D surface or the traditional 2D spectrum.', synonyms: ['view', '3d', 'traditional', '2d'], targetId: 'view-3d', targetKind: 'toggle', mainScreen: 'always', parityStatus: 'wired' }),
  entry({ id: 'display.colormap', section: 'display', label: 'Colour map', description: 'Heat palette for the waterfall; Classic keeps the previous palette.', synonyms: ['palette', 'classic', 'colormap'], targetId: 'terrain-palette', targetKind: 'select', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'display.3d.depth', section: 'display', label: '3D history rows', description: 'How many spectrum rows the 3D surface stacks.', synonyms: ['depth', 'rows', 'history'], targetId: 'terrain-depth', targetKind: 'slider', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'display.3d.height', section: 'display', label: '3D surface height', description: 'Vertical exaggeration of the 3D surface.', synonyms: ['height'], targetId: 'terrain-height', targetKind: 'slider', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'display.3d.elevation', section: 'display', label: 'Camera elevation', description: 'Viewing angle of the 3D surface.', synonyms: ['elevation', 'tilt'], targetId: 'terrain-elevation', targetKind: 'slider', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'display.3d.farField', section: 'display', label: 'Far-field width', description: 'How much older rows recede toward the back of the 3D surface.', synonyms: ['perspective', 'far field'], targetId: 'terrain-perspective', targetKind: 'slider', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'display.3d.floor', section: 'display', label: '3D floor level', description: 'Relative dB mapped to the bottom of the 3D surface.', synonyms: ['floor'], targetId: 'terrain-floor', targetKind: 'slider', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'display.3d.ceiling', section: 'display', label: '3D ceiling level', description: 'Relative dB mapped to the top of the 3D surface.', synonyms: ['ceiling'], targetId: 'terrain-ceiling', targetKind: 'slider', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'display.3d.perspective.band', section: 'display', label: '3D fit range', description: 'Fit the 3D range to the signals currently on screen.', synonyms: ['fit', 'range'], targetId: 'terrain-fit-range', targetKind: 'button', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'display.split', section: 'display', label: '3D and waterfall split', description: 'How much height the 3D view takes above the flat waterfall.', synonyms: ['split', 'splitter'], targetId: 'terrain-split', targetKind: 'slider', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'display.span', section: 'display', label: 'Span', description: 'Visible frequency span.', synonyms: ['span'], targetId: 'sample-rate-readout', targetKind: 'readout', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'display.status', section: 'display', label: 'Display status', description: 'Spectrum data source and freshness message.', synonyms: ['display caption', 'waiting for TCI', 'spectrum data'], targetId: 'display-caption', targetKind: 'readout', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'display.zoom', section: 'display', label: 'Display zoom', description: 'Zoom the visible span without retuning.', synonyms: ['zoom'], targetId: 'display-zoom', targetKind: 'slider', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'display.pause', section: 'display', label: 'Pause display', description: 'Freeze the waterfall and spectrum; reception keeps running.', synonyms: ['pause', 'freeze'], targetId: 'display-pause', targetKind: 'button', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'display.averaging', section: 'display', label: 'Averaging', description: 'Number of spectrum frames averaged before drawing.', synonyms: ['avg', 'average'], targetId: 'display-spectrum-average', targetKind: 'slider', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'display.tunePeak', section: 'display', label: 'Tune to peak', description: 'Move the VFO to the strongest visible signal.', synonyms: ['tune peak'], targetId: 'display-peak-tune-assist', targetKind: 'toggle', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'display.stayAwake', section: 'display', label: 'Stay awake', description: 'Keep the screen awake while the console is open.', synonyms: ['wake lock', 'screen'], targetId: 'saturn.remote.keepScreenAwake', targetKind: 'storage-key', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'display.history', section: 'display', label: 'Waterfall history', description: 'How long the flat waterfall keeps scrolling back.', synonyms: ['history'], targetId: 'terrain-status', targetKind: 'readout', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'display.bandEdges', section: 'display', label: 'Band edge markers', description: 'Show band limit markers inside the display well.', synonyms: ['band edges'], targetId: 'display-show-band-edges', targetKind: 'toggle', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'display.diagnostics', section: 'display', label: 'Terrain diagnostics', description: 'Overlay 3D geometry diagnostics for troubleshooting.', synonyms: ['diagnostics', 'terrain'], targetId: 'terrain-diagnostics-enabled', targetKind: 'toggle', mainScreen: 'settings-only', parityStatus: 'wired' }),

  // ---- Meter (build sheet §8.3) ----
  entry({ id: 'meter.type', section: 'meter', label: 'Meter type', description: 'What the meter shows: signal strength, power, SWR, ALC or compression.', synonyms: ['meter', 's-meter', 'sql', 'power', 'swr', 'alc'], targetId: 'instrument-meter-mode', targetKind: 'select', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'meter.average', section: 'meter', label: 'Meter averaging', description: 'Average or peak-hold response.', synonyms: ['avg', 'peak', 'avg mode'], targetId: 'instrument-meter-average-btn', targetKind: 'select', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'meter.readout', section: 'meter', label: 'Meter readout', description: 'S-unit and dBm reading with peak value.', synonyms: ['s9', 'dbm', 'peak'], targetId: 'meter-readout', targetKind: 'readout', mainScreen: 'always', parityStatus: 'wired' }),
  entry({ id: 'meter.dbfsBars', section: 'meter', label: 'Left and right dBFS bars', description: 'Stereo audio level bars for the receive stream.', synonyms: ['dbfs', 'levels'], targetId: 'instrument-rx-audio-meters', targetKind: 'readout', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'meter.details', section: 'meter', label: 'More meter details and TX tools', description: 'Expanded meter detail and transmit tool disclosure.', synonyms: ['meter details', 'tx tools'], targetId: 'meter-details-disclosure', targetKind: 'overlay', mainScreen: 'optional', parityStatus: 'wired' }),

  // ---- Receive (build sheet §8.6) ----
  entry({ id: 'receive.startStop', section: 'receive', label: 'Start or stop audio', description: 'Start and stop receiver audio in the browser.', synonyms: ['stop audio', 'start audio'], targetId: 'rx-audio-toggle-btn', targetKind: 'button', domTextToken: 'Audio', mainScreen: 'always', parityStatus: 'wired' }),
  entry({ id: 'receive.volume', section: 'receive', label: 'Receive volume', description: 'Browser-side receiver volume.', synonyms: ['volume', 'af gain'], targetId: 'rx-volume', targetKind: 'slider', mainScreen: 'always', parityStatus: 'wired' }),
  entry({ id: 'receive.headphones', section: 'receive', label: 'G2 rear headphones', description: 'Play receiver audio through the rear G2 headphone jack while in RX.', synonyms: ['headphone', 'rear jack', 'local audio'], targetId: 'rx-headphones-btn', targetKind: 'toggle', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'receive.buffer', section: 'receive', label: 'Audio buffer', description: 'Playback buffer health: rate, lead, resyncs and path.', synonyms: ['buffer', 'lead', 'resync'], targetId: 'audio-buffer-status', targetKind: 'readout', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'receive.voiceSquelch', section: 'receive', label: 'Voice squelch', description: 'Mute receive audio when no voice is detected.', synonyms: ['sql', 'squelch', 'voice sql'], targetId: 'rx-ssql-btn', targetKind: 'toggle', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'receive.voiceSquelchLevel', section: 'receive', label: 'Voice squelch level', description: 'Threshold for the voice squelch detector.', synonyms: ['sql level', 'squelch level', 'voice 16'], targetId: 'rx-ssql-threshold', targetKind: 'slider', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'receive.agc', section: 'receive', label: 'AGC speed', description: 'Automatic gain control time constant.', synonyms: ['agc', 'off', 'long', 'slow', 'med', 'fast'], targetId: 'rx-agc-grid', targetKind: 'select', mainScreen: 'always', parityStatus: 'wired' }),
  entry({ id: 'receive.agcGain', section: 'receive', label: 'AGC gain', description: 'Manual gain applied on top of the AGC.', synonyms: ['agc gain'], targetId: 'agc-gain', targetKind: 'slider', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'receive.anf', section: 'receive', label: 'Automatic notch filter', description: 'Track and remove steady carriers automatically.', synonyms: ['anf', 'notch'], targetId: 'rx-anf-btn', targetKind: 'toggle', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'receive.nr', section: 'receive', label: 'Noise reduction', description: 'Spectral noise reduction and its level.', synonyms: ['nr', 'nr2'], targetId: 'setup-dsp-nr-mode', targetKind: 'select', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'receive.nb', section: 'receive', label: 'Noise blanker', description: 'Impulse noise blanker and its threshold.', synonyms: ['nb', 'blanker'], targetId: 'mobile-nb-btn', targetKind: 'toggle', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'receive.filterLow', section: 'receive', label: 'Filter low cut', description: 'Lower edge of the receive passband.', synonyms: ['low cut', 'filter'], targetId: 'filter-low', targetKind: 'slider', mainScreen: 'always', parityStatus: 'wired' }),
  entry({ id: 'receive.filterHigh', section: 'receive', label: 'Filter high cut', description: 'Upper edge of the receive passband.', synonyms: ['high cut', 'filter'], targetId: 'filter-high', targetKind: 'slider', mainScreen: 'always', parityStatus: 'wired' }),
  entry({ id: 'receive.passband', section: 'receive', label: 'Passband overlay', description: 'Drag the passband handles directly on the display.', synonyms: ['passband'], targetId: 'filter-window', targetKind: 'overlay', mainScreen: 'always', parityStatus: 'wired' }),
  entry({ id: 'receive.codec', section: 'receive', label: 'RX audio codec', description: 'Opus or uncompressed PCM over the WebSocket media lane.', synonyms: ['opus', 'pcm', 'codec', 'rx_audio_codec'], targetId: 'rx_audio_codec', targetKind: 'query-param', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'receive.codecDiagnostics', section: 'receive', label: 'RX codec diagnostics', description: 'Live codec, decode health, jitter and underrun counters.', synonyms: ['codec diagnostics', 'opus'], targetId: 'setup-network-copy-diagnostics-btn', targetKind: 'button', mainScreen: 'settings-only', parityStatus: 'wired' }),

  // ---- Transmit (build sheet §8.7, §10) ----
  entry({ id: 'transmit.arm', section: 'transmit', label: 'Arm transmit', description: 'Arm the transmitter; PTT cannot key until armed.', synonyms: ['arm', 'tap to arm'], targetId: 'tx-arm-btn', targetKind: 'button', mainScreen: 'always', safetyPinned: true, parityStatus: 'wired', domTextToken: 'TX' }),
  entry({ id: 'transmit.ptt', section: 'transmit', label: 'Hold PTT', description: 'Momentary push to talk; releasing on pointer up, cancel or blur unkeys.', synonyms: ['ptt', 'push to talk'], targetId: 'ptt-btn', targetKind: 'button', mainScreen: 'always', safetyPinned: true, parityStatus: 'wired', domTextToken: 'PTT' }),
  entry({ id: 'transmit.mox', section: 'transmit', label: 'MOX', description: 'Toggle transmit without holding PTT.', synonyms: ['mox', 'vox'], targetId: 'mox-btn', targetKind: 'toggle', domTextToken: 'MOX', mainScreen: 'always', safetyPinned: true, parityStatus: 'wired' }),
  entry({ id: 'transmit.lock', section: 'transmit', label: 'Lock transmit', description: 'Lock transmit immediately.', synonyms: ['locked', 'lock'], targetId: 'tx-lock-btn', targetKind: 'button', domTextToken: 'Lock', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'transmit.state', section: 'transmit', label: 'TX state indicator', description: 'Locked, ready, armed, keying or on air.', synonyms: ['tx state', 'tx locked', 'on air'], targetId: 'tx-zone-state', targetKind: 'indicator', mainScreen: 'always', sourceControlIds: ['app-tx-state-badge'], parityStatus: 'wired' }),
  entry({ id: 'transmit.readyCountdown', section: 'transmit', label: 'Arm window countdown', description: 'Time left before the arm window expires and needs reconfirming.', synonyms: ['countdown', 'idle timeout'], targetId: 'tx-ready-countdown', targetKind: 'readout', mainScreen: 'always', parityStatus: 'wired' }),
  entry({ id: 'transmit.micLevel', section: 'transmit', label: 'Microphone level', description: 'Transmit microphone level readout.', synonyms: ['mic', 'mic gain'], targetId: 'tx-zone-mic-value', targetKind: 'readout', mainScreen: 'always', parityStatus: 'wired' }),
  entry({ id: 'transmit.power', section: 'transmit', label: 'Forward power', description: 'Transmit power in watts.', synonyms: ['power', 'watts'], targetId: 'tx-zone-power-value', targetKind: 'readout', mainScreen: 'always', parityStatus: 'wired' }),
  entry({ id: 'transmit.swr', section: 'transmit', label: 'SWR', description: 'Standing wave ratio while transmitting.', synonyms: ['swr'], targetId: 'tx-zone-swr-value', targetKind: 'readout', mainScreen: 'always', parityStatus: 'wired' }),
  entry({ id: 'transmit.audioSource', section: 'transmit', label: 'TX audio source', description: 'Where transmit audio comes from.', synonyms: ['satp', 'native', 'tx source'], targetId: 'tx-audio-source', targetKind: 'select', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'transmit.pairNative', section: 'transmit', label: 'Pair native sender', description: 'Pair and inspect the native TX audio sender.', synonyms: ['native', 'satp', 'pair'], targetId: 'satp-pair-btn', targetKind: 'button', domTextToken: 'Pair native sender', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'transmit.monitor', section: 'transmit', label: 'Monitor transmit audio', description: 'Listen to transmit audio locally; this never keys the radio.', synonyms: ['mon', 'monitor'], targetId: 'tx-mon-btn', targetKind: 'toggle', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'transmit.monitorLevel', section: 'transmit', label: 'Monitor level', description: 'Level for the local transmit-audio monitor.', synonyms: ['mon level'], targetId: 'tx-mon-level', targetKind: 'slider', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'transmit.drive', section: 'transmit', label: 'TX drive', description: 'Drive level sent to the radio.', synonyms: ['drive', 'tx level'], targetId: 'tx-drive', targetKind: 'slider', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'transmit.micGain', section: 'transmit', label: 'Microphone gain', description: 'Analogue microphone gain.', synonyms: ['mic gain'], targetId: 'tx-mic-gain', targetKind: 'slider', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'transmit.filterLow', section: 'transmit', label: 'TX filter low cut', description: 'Lower edge of the transmit passband.', synonyms: ['tx filter'], targetId: 'tx-filter-low', targetKind: 'slider', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'transmit.filterHigh', section: 'transmit', label: 'TX filter high cut', description: 'Upper edge of the transmit passband.', synonyms: ['tx filter'], targetId: 'tx-filter-high', targetKind: 'slider', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'transmit.eq', section: 'transmit', label: 'TX equaliser', description: 'Transmit audio equaliser bands.', synonyms: ['eq', 'tx eq'], targetId: 'tx-eq-enable-btn', targetKind: 'toggle', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'transmit.cfc', section: 'transmit', label: 'Continuous frequency compression', description: 'Transmit CFC and pre-compensation.', synonyms: ['cfc', 'tx_cfc'], targetId: 'tx_cfc', targetKind: 'query-param', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'transmit.noiseGate', section: 'transmit', label: 'TX noise gate', description: 'Gate transmit audio below a threshold.', synonyms: ['noise gate', 'tx_noise_gate'], targetId: 'tx-noise-gate-enabled', targetKind: 'toggle', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'transmit.dexp', section: 'transmit', label: 'TX downward expander', description: 'Downward expander threshold and ratio.', synonyms: ['dexp', 'expander'], targetId: 'tx-dexp-enabled', targetKind: 'toggle', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'transmit.speechProcessor', section: 'transmit', label: 'Speech processor', description: 'Speech processing and its gain.', synonyms: ['speech', 'processor'], targetId: 'tx-speech-processor-enabled', targetKind: 'toggle', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'transmit.cessb', section: 'transmit', label: 'CESSB', description: 'Controlled envelope SSB transmit shaping.', synonyms: ['cessb'], targetId: 'tx-cessb-enabled', targetKind: 'toggle', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'transmit.puresignal', section: 'transmit', label: 'PureSignal', description: 'Predistortion calibration and feedback.', synonyms: ['puresignal', 'predistortion'], targetId: 'setup-tx-puresignal-enabled', targetKind: 'toggle', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'transmit.phaseRotator', section: 'transmit', label: 'Phase rotator', description: 'Transmit phase rotator and corner frequency.', synonyms: ['phase rotator'], targetId: 'setup-tx-phase-rotator-enabled', targetKind: 'toggle', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'transmit.twoTone', section: 'transmit', label: 'Two-tone test', description: 'Two-tone generator for transmit testing.', synonyms: ['two tone', 'twotone'], targetId: 'setup-tx-two-tone-section', targetKind: 'overlay', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'transmit.timeout', section: 'transmit', label: 'TX timeout', description: 'Maximum transmit time before it is stopped.', synonyms: ['timeout'], targetId: 'setup-tx-timeout-enabled', targetKind: 'toggle', mainScreen: 'settings-only', parityStatus: 'wired' }),

  // ---- Radio (build sheet §8.2, §8.4, §8.8) ----
  entry({ id: 'radio.vfoA', section: 'radio', label: 'VFO A frequency', description: 'Main receive frequency.', synonyms: ['vfo', 'frequency'], targetId: 'dds-readout', targetKind: 'readout', mainScreen: 'always', safetyPinned: true, parityStatus: 'wired' }),
  entry({ id: 'radio.vfoB', section: 'radio', label: 'VFO B', description: 'Second VFO and split state.', synonyms: ['vfo b', 'split'], targetId: 'vfo-b-select-btn', targetKind: 'button', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'radio.reference', section: 'radio', label: 'VFO reference', description: 'Which VFO drives transmit.', synonyms: ['reference', 'a rx', 'tx vfo'], targetId: 'vfo-a-select-btn', targetKind: 'toggle', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'radio.split', section: 'radio', label: 'Split operation', description: 'Receive and transmit on different VFOs.', synonyms: ['split'], targetId: 'split-toggle-btn', targetKind: 'toggle', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'radio.band', section: 'radio', label: 'Band', description: 'Band selection and band memories.', synonyms: ['band', '160m', '80m'], targetId: 'band-grid', targetKind: 'select', mainScreen: 'always', sourceControlIds: ['vfo-band-tag'], parityStatus: 'wired' }),
  entry({ id: 'radio.mode', section: 'radio', label: 'Demodulation mode', description: 'USB, LSB, CW, AM, DSB, FM and the digital modes.', synonyms: ['mode', 'usb', 'lsb', 'dsb', 'double sideband', 'wfm'], targetId: 'mode-grid', targetKind: 'select', mainScreen: 'always', sourceControlIds: ['vfo-mode-tag'], parityStatus: 'wired' }),
  entry({ id: 'radio.wbfmDeemphasis', section: 'radio', label: 'WFM de-emphasis', description: 'Broadcast FM de-emphasis time constant.', synonyms: ['wbfm', 'deemphasis'], targetId: 'wbfm-deemphasis', targetKind: 'select', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'radio.tuneStep', section: 'radio', label: 'Tuning step', description: 'Step used by wheel, arrows and swipe tuning.', synonyms: ['step', 'tune step'], targetId: 'saturn.remote.vfoTuneStepHz', targetKind: 'storage-key', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'radio.freqLock', section: 'radio', label: 'Frequency lock', description: 'Lock the VFO against accidental tuning.', synonyms: ['lock', 'freq lock'], targetId: 'saturn.remote.freqLock', targetKind: 'storage-key', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'radio.bandMemory', section: 'radio', label: 'Band memories', description: 'Automatically stored per-band operating state.', synonyms: ['memory', 'band memory'], targetId: 'saturn.remote.bandMemory', targetKind: 'storage-key', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'radio.rxInput', section: 'radio', label: 'RX input', description: 'Receive ADC selection; fixed on this radio.', synonyms: ['adc', 'rx input'], targetId: 'path-summary', targetKind: 'readout', mainScreen: 'always', parityStatus: 'wired' }),
  entry({ id: 'radio.antenna', section: 'radio', label: 'RX antenna', description: 'Receive antenna selection.', synonyms: ['ant', 'antenna'], targetId: 'rx-antenna', targetKind: 'select', mainScreen: 'always', sourceControlIds: ['vfo-antenna-pill'], parityStatus: 'wired' }),
  entry({ id: 'radio.attenuator', section: 'radio', label: 'Attenuator', description: 'Receive attenuation in dB.', synonyms: ['att', 'attenuator', 'att off'], targetId: 'rx-attenuation', targetKind: 'select', mainScreen: 'always', parityStatus: 'wired' }),
  entry({ id: 'radio.profiles', section: 'radio', label: 'Remote profiles', description: 'Saved remote settings profiles, including delete.', synonyms: ['profile', 'profiles'], targetId: 'setup-panel-profiles', targetKind: 'overlay', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'radio.radioPrefs', section: 'radio', label: 'Radio preferences', description: 'Stored radio preference set for this browser.', synonyms: ['prefs', 'radio prefs'], targetId: 'saturn.remote.radioPrefs', targetKind: 'storage-key', mainScreen: 'settings-only', parityStatus: 'wired' }),

  // ---- Audio ----
  entry({ id: 'audio.inputDevice', section: 'audio', label: 'Microphone input', description: 'Browser microphone device for transmit audio.', synonyms: ['input', 'device', 'mic'], targetId: 'saturn.remote.audioInputDeviceId', targetKind: 'storage-key', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'audio.outputDevice', section: 'audio', label: 'Audio output', description: 'Browser output device for receive audio.', synonyms: ['output', 'device', 'speaker'], targetId: 'saturn.remote.audioOutputDeviceId', targetKind: 'storage-key', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'audio.adaptiveRate', section: 'audio', label: 'Adaptive playback rate', description: 'Adjust playback rate to hold the audio buffer steady.', synonyms: ['adaptive', 'rx_audio_adaptive'], targetId: 'rx_audio_adaptive', targetKind: 'query-param', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'audio.scope', section: 'audio', label: 'Audio scope', description: 'Receive audio scope and meters.', synonyms: ['scope'], targetId: 'operations-panel-audio', targetKind: 'overlay', mainScreen: 'optional', parityStatus: 'wired' }),

  // ---- Network ----
  entry({ id: 'network.status', section: 'network', label: 'Connection status', description: 'Bridge connection state and reconnect supervision; opens status details.', synonyms: ['connection', 'reconnect'], targetId: 'operator-conn-pill', targetKind: 'indicator', domTextToken: 'Connection', mainScreen: 'always', parityStatus: 'wired' }),
  entry({ id: 'network.statusValue', section: 'network', label: 'Connection state text', description: 'Connected, reconnecting or offline.', synonyms: ['connection state', 'online'], targetId: 'operator-conn-value', targetKind: 'readout', mainScreen: 'always', parityStatus: 'wired' }),
  entry({ id: 'network.rtt', section: 'network', label: 'Round-trip time', description: 'Bridge round-trip latency.', synonyms: ['rtt', 'latency', 'ping'], targetId: 'operator-latency-value', targetKind: 'readout', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'network.transport', section: 'network', label: 'Transport', description: 'LAN raw IQ or WAN server-computed spectrum rows.', synonyms: ['transport', 'lan iq', 'wan'], targetId: 'operator-transport-value', targetKind: 'indicator', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'network.wsUrl', section: 'network', label: 'Bridge address', description: 'The websocket address the console is live on.', synonyms: ['wss', 'url', 'live on'], targetId: 'ws-url', targetKind: 'control', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'network.goOffline', section: 'network', label: 'Go offline', description: 'Disconnect the console from the bridge.', synonyms: ['offline', 'disconnect'], targetId: 'system-go-offline-btn', targetKind: 'button', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'network.goLive', section: 'network', label: 'Go live', description: 'Connect the console to the bridge; also cancels a pending connection.', synonyms: ['go live', 'connect', 'cancel'], targetId: 'go-live-btn', targetKind: 'button', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'network.splitTransport', section: 'network', label: 'Split websockets', description: 'Use separate control and media websockets.', synonyms: ['transport', 'split', 'phase42_split'], targetId: 'transport', targetKind: 'query-param', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'network.legacySocket', section: 'network', label: 'Legacy single socket', description: 'Diagnostic mode using one combined websocket.', synonyms: ['legacy', 'force_legacy_ws'], targetId: 'force_legacy_ws', targetKind: 'query-param', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'network.diagnostics', section: 'network', label: 'Operator diagnostics', description: 'Copy the operator log and live client trace.', synonyms: ['diagnostics', 'log', 'copy'], targetId: 'setup-network-copy-diagnostics-btn', targetKind: 'button', mainScreen: 'settings-only', parityStatus: 'wired' }),

  // ---- Memory and log ----
  entry({ id: 'memory.saveCurrent', section: 'memory', label: 'Save current memory', description: 'Store the current band state into the memory list.', synonyms: ['memory', 'save'], targetId: 'operations-memory-save-btn', targetKind: 'button', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'log.operatorLog', section: 'log', label: 'Operator log', description: 'Timestamped operator-visible event log.', synonyms: ['log', 'operator log'], targetId: 'operations-panel-log', targetKind: 'overlay', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'log.liveTrace', section: 'log', label: 'Live client trace', description: 'Live websocket and client trace for troubleshooting.', synonyms: ['trace', 'live trace'], targetId: 'operations-tab-log', targetKind: 'button', mainScreen: 'settings-only', parityStatus: 'wired' }),

  // ---- Interface ----
  entry({ id: 'interface.theme', section: 'interface', label: 'Theme', description: 'Auto, dark or light presentation.', synonyms: ['theme', 'dark', 'light'], targetId: 'theme-btn', targetKind: 'button', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'interface.phoneView', section: 'interface', label: 'Phone view', description: 'Use the dedicated phone layout instead of the responsive console.', synonyms: ['phone', 'mobile'], targetId: 'layout-btn', targetKind: 'button', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'interface.keyboardShortcuts', section: 'interface', label: 'Keyboard shortcuts', description: 'Shortcut reference, including hold-Space PTT.', synonyms: ['shortcuts', 'help', 'keys'], targetId: 'shortcut-help-btn', targetKind: 'button', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'interface.displayPrefs', section: 'interface', label: 'Display preferences', description: 'Stored display preferences for this browser.', synonyms: ['display prefs'], targetId: 'saturn.remote.displayPrefs', targetKind: 'storage-key', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'interface.meterMode', section: 'interface', label: 'Meter mode memory', description: 'Last used meter mode for this browser.', synonyms: ['meter mode'], targetId: 'saturn.remote.instrumentMeterMode', targetKind: 'storage-key', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'interface.operationsDrawer', section: 'interface', label: 'Last Operations panel', description: 'Which operations panel was last open.', synonyms: ['operations'], targetId: 'saturn.remote.operationsDrawer', targetKind: 'storage-key', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'interface.setupPanel', section: 'interface', label: 'Last Settings section', description: 'Which settings section was last open.', synonyms: ['settings', 'setup'], targetId: 'saturn.remote.setupPanel', targetKind: 'storage-key', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'interface.phoneSpectrum', section: 'interface', label: 'Phone spectrum mode', description: 'Phone-view spectrum mode preference.', synonyms: ['phone spectrum'], targetId: 'saturn.remote.phoneSpectrumMode', targetKind: 'storage-key', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'interface.phoneWaterfall', section: 'interface', label: 'Phone waterfall', description: 'Phone-view waterfall preference.', synonyms: ['phone waterfall'], targetId: 'saturn.remote.phoneWaterfall', targetKind: 'storage-key', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'interface.activeProfile', section: 'interface', label: 'Active profile', description: 'Currently selected remote settings profile.', synonyms: ['profile'], targetId: 'saturn.remote.activeProfile', targetKind: 'storage-key', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'interface.splitRatio', section: 'interface', label: 'Display split ratio', description: 'Stored 3D and waterfall height ratio.', synonyms: ['split'], targetId: 'saturn.remote.spectrumWaterfallRatio', targetKind: 'storage-key', mainScreen: 'settings-only', parityStatus: 'wired' }),

  // ---- About and system ----
  entry({ id: 'about.device', section: 'about', label: 'Radio', description: 'Connected radio model and firmware.', synonyms: ['device', 'anan', 'firmware'], targetId: 'static-wsdiag-marker', targetKind: 'readout', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'about.wsProbe', section: 'about', label: 'Websocket probe', description: 'Probe the bridge websocket from the browser.', synonyms: ['probe', 'ws probe'], targetId: 'static-wsdiag-btn', targetKind: 'button', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'about.copyLog', section: 'about', label: 'Copy log', description: 'Copy the console diagnostic log.', synonyms: ['copy log', 'log'], targetId: 'static-wsdiag-copy-btn', targetKind: 'button', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'about.saturnGo', section: 'about', label: 'Saturn Go', description: 'Open the Saturn Go management interface.', synonyms: ['saturn go', 'manage'], targetId: 'saturn-manage-home', targetKind: 'button', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'about.monitor', section: 'about', label: 'System monitor', description: 'Open system monitoring for the appliance.', synonyms: ['monitor'], targetId: 'saturn-manage-monitor', targetKind: 'button', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'about.txDiagnostic', section: 'about', label: 'TX diagnostic mode', description: 'Diagnostic transmit source override.', synonyms: ['tx_diagnostic', 'diagnostic'], targetId: 'tx_diagnostic', targetKind: 'query-param', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'about.txLevelOverride', section: 'about', label: 'TX level override', description: 'Diagnostic transmit level override.', synonyms: ['tx_level_db'], targetId: 'tx_level_db', targetKind: 'query-param', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'about.displayProfile', section: 'about', label: 'Display profile', description: 'Preset display and audio profile from the URL.', synonyms: ['display_profile', 'profile'], targetId: 'display_profile', targetKind: 'query-param', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'about.txSource', section: 'about', label: 'TX source override', description: 'Diagnostic transmit source selection.', synonyms: ['tx_source'], targetId: 'tx_source', targetKind: 'query-param', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'about.txOpus', section: 'about', label: 'TX Opus codec', description: 'Advertise the Opus transmit codec.', synonyms: ['tx_opus', 'opus'], targetId: 'tx_opus', targetKind: 'query-param', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'about.txVoiceEq', section: 'about', label: 'TX voice equaliser', description: 'Diagnostic voice equaliser preset.', synonyms: ['tx_voice_eq', 'eq'], targetId: 'tx_voice_eq', targetKind: 'query-param', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'about.txCfcPrecomp', section: 'about', label: 'TX CFC pre-compensation', description: 'Diagnostic CFC pre-compensation level.', synonyms: ['tx_cfc_precomp_db'], targetId: 'tx_cfc_precomp_db', targetKind: 'query-param', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'about.txNoiseGate', section: 'about', label: 'TX noise gate diagnostic', description: 'Diagnostic noise-gate switch and threshold.', synonyms: ['tx_noise_gate', 'tx_noise_gate_db'], targetId: 'tx_noise_gate', targetKind: 'query-param', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'about.txNoiseGateThreshold', section: 'about', label: 'TX noise gate threshold', description: 'Diagnostic noise-gate threshold override.', synonyms: ['tx_noise_gate_db', 'noise gate'], targetId: 'tx_noise_gate_db', targetKind: 'query-param', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'interface.splitTransportAlias', section: 'interface', label: 'Split websocket alias', description: 'Legacy parameter for the split websocket transport.', synonyms: ['phase42_split', 'split'], targetId: 'phase42_split', targetKind: 'query-param', mainScreen: 'settings-only', parityStatus: 'wired' }),

  // ---- Display: legacy effects and 2D controls promoted from the gap audit ----
  entry({ id: 'display.clarity', section: 'display', label: 'Transceiver clarity', description: 'Overall screen clarity and contrast treatment.', synonyms: ['clarity'], targetId: 'display-transceiver-clarity', targetKind: 'slider', mainScreen: 'settings-only', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'display.appearanceUndo', section: 'display', label: 'Undo appearance change', description: 'Revert the last display appearance change.', synonyms: ['undo'], targetId: 'display-appearance-undo', targetKind: 'button', mainScreen: 'settings-only', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'display.spectrumAutoRange', section: 'display', label: 'Spectrum auto range', description: 'Scale the spectrum automatically to the signal range.', synonyms: ['auto range'], targetId: 'display-spectrum-auto-range', targetKind: 'toggle', mainScreen: 'settings-only', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'display.waterfallAutoRange', section: 'display', label: 'Waterfall auto range', description: 'Scale the waterfall automatically to the signal range.', synonyms: ['auto range'], targetId: 'display-waterfall-auto-range', targetKind: 'toggle', mainScreen: 'settings-only', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'display.spectrumFloor', section: 'display', label: 'Spectrum floor', description: 'Lowest level shown on the 2D spectrum.', synonyms: ['floor'], targetId: 'display-spectrum-floor', targetKind: 'slider', mainScreen: 'settings-only', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'display.spectrumCeiling', section: 'display', label: 'Spectrum ceiling', description: 'Highest level shown on the 2D spectrum.', synonyms: ['ceiling'], targetId: 'display-spectrum-ceiling', targetKind: 'slider', mainScreen: 'settings-only', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'display.waterfallFloor', section: 'display', label: 'Waterfall floor', description: 'Lowest level in the waterfall colour range.', synonyms: ['floor'], targetId: 'display-waterfall-floor', targetKind: 'slider', mainScreen: 'settings-only', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'display.waterfallCeiling', section: 'display', label: 'Waterfall ceiling', description: 'Highest level in the waterfall colour range.', synonyms: ['ceiling'], targetId: 'display-waterfall-ceiling', targetKind: 'slider', mainScreen: 'settings-only', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'display.traceColor', section: 'display', label: 'Spectrum trace colour', description: 'Colour of the 2D spectrum trace.', synonyms: ['colour', 'trace'], targetId: 'display-spectrum-trace-color', targetKind: 'select', mainScreen: 'settings-only', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'display.traceSmoothing', section: 'display', label: 'Trace smoothing', description: 'Smoothing applied to the spectrum trace.', synonyms: ['smoothing'], targetId: 'display-spectrum-trace-smoothing', targetKind: 'slider', mainScreen: 'settings-only', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'display.traceFill', section: 'display', label: 'Trace fill', description: 'Fill under the spectrum trace.', synonyms: ['fill'], targetId: 'display-spectrum-trace-fill', targetKind: 'toggle', mainScreen: 'settings-only', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'display.peakGlow', section: 'display', label: 'Peak glow', description: 'Glow effect on spectrum peaks.', synonyms: ['glow', 'peak'], targetId: 'display-spectrum-peak-glow', targetKind: 'toggle', mainScreen: 'settings-only', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'display.glassSheen', section: 'display', label: 'Glass sheen', description: 'Sheen overlay on the display well.', synonyms: ['sheen'], targetId: 'display-spectrum-glass-sheen', targetKind: 'toggle', mainScreen: 'settings-only', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'display.waterfallSpeed', section: 'display', label: 'Waterfall speed', description: 'Scroll speed of the flat waterfall.', synonyms: ['speed', 'waterfall'], targetId: 'display-waterfall-speed', targetKind: 'slider', mainScreen: 'settings-only', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'display.waterfallContrast', section: 'display', label: 'Waterfall contrast', description: 'Contrast of the waterfall colours.', synonyms: ['contrast'], targetId: 'display-waterfall-contrast', targetKind: 'slider', mainScreen: 'settings-only', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'display.waterfallSmoothing', section: 'display', label: 'Waterfall smoothing', description: 'Smoothing between waterfall rows.', synonyms: ['smoothing'], targetId: 'display-waterfall-smoothing', targetKind: 'slider', mainScreen: 'settings-only', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'display.waterfallPalette', section: 'display', label: 'Waterfall palette', description: 'Colour palette used by the flat waterfall.', synonyms: ['palette', 'colormap'], targetId: 'display-waterfall-palette', targetKind: 'select', mainScreen: 'settings-only', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'display.spectrumPeakHold', section: 'display', label: 'Spectrum peak hold', description: 'Hold spectrum peaks in the 2D view.', synonyms: ['peak hold'], targetId: 'display-spectrum-peak-hold', targetKind: 'toggle', mainScreen: 'optional', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'display.enhancedColors', section: 'display', label: 'Enhanced colours', description: 'Use the enhanced display colour set.', synonyms: ['colours'], targetId: 'display-spectrum-enhanced-colors', targetKind: 'toggle', mainScreen: 'settings-only', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'display.showGrid', section: 'display', label: 'Show grid', description: 'Draw the display grid lines.', synonyms: ['grid'], targetId: 'display-show-grid', targetKind: 'toggle', mainScreen: 'optional', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'display.showCenterLine', section: 'display', label: 'Show center line', description: 'Draw the center frequency line.', synonyms: ['center line'], targetId: 'display-show-center-line', targetKind: 'toggle', mainScreen: 'optional', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'display.centerAction', section: 'display', label: 'Center display', description: 'Center the display on the current VFO.', synonyms: ['center'], targetId: 'display-center-btn', targetKind: 'button', mainScreen: 'optional', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'display.waterfallToggle', section: 'display', label: 'Waterfall on or off', description: 'Show or hide the flat waterfall.', synonyms: ['waterfall'], targetId: 'waterfall-toggle-btn', targetKind: 'toggle', mainScreen: 'optional', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'display.viewTraditional', section: 'display', label: 'Traditional view', description: 'Switch to the traditional 2D spectrum.', synonyms: ['traditional', '2d'], targetId: 'view-traditional', targetKind: 'button', mainScreen: 'optional', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'display.terrainSettings', section: 'display', label: '3D settings', description: 'Open the 3D surface settings.', synonyms: ['terrain', '3d'], targetId: 'terrain-settings-open', targetKind: 'button', mainScreen: 'optional', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'display.terrainMode', section: 'display', label: '3D or traditional surface', description: 'Choose the 3D surface or the traditional waterfall in the 3D pane.', synonyms: ['terrain mode'], targetId: 'terrain-mode', targetKind: 'select', mainScreen: 'optional', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'display.terrainGamma', section: 'display', label: '3D gamma', description: 'Gamma applied to 3D amplitudes.', synonyms: ['gamma'], targetId: 'terrain-gamma', targetKind: 'slider', mainScreen: 'settings-only', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'display.terrainCleanup', section: 'display', label: '3D noise cleanup', description: 'Noise cleanup applied to the 3D surface.', synonyms: ['cleanup'], targetId: 'terrain-cleanup', targetKind: 'slider', mainScreen: 'settings-only', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'display.terrainWaterfallCleanup', section: 'display', label: '3D waterfall cleanup', description: 'Cleanup applied to the 3D waterfall.', synonyms: ['cleanup'], targetId: 'terrain-waterfallCleanup', targetKind: 'slider', mainScreen: 'settings-only', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'display.terrainCleanupBaseline', section: 'display', label: 'Cleanup baseline', description: 'Baseline used by the noise cleanup.', synonyms: ['baseline'], targetId: 'terrain-cleanupBaseline', targetKind: 'control', mainScreen: 'settings-only', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'display.terrainNoiseEstimate', section: 'display', label: 'Estimate noise floor', description: 'Re-estimate the noise floor from the current history.', synonyms: ['noise floor'], targetId: 'terrain-noise-estimate', targetKind: 'button', mainScreen: 'settings-only', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'display.terrainSmoothing', section: 'display', label: '3D smoothing', description: 'Smoothing across 3D age rows.', synonyms: ['smoothing'], targetId: 'terrain-smoothing', targetKind: 'slider', mainScreen: 'settings-only', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'display.terrainQuality', section: 'display', label: '3D quality', description: 'Quality tier for the 3D surface.', synonyms: ['quality'], targetId: 'terrain-quality', targetKind: 'select', mainScreen: 'settings-only', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'display.terrainGridOpacity', section: 'display', label: '3D grid opacity', description: 'Opacity of the 3D grid.', synonyms: ['grid'], targetId: 'terrain-gridOpacity', targetKind: 'slider', mainScreen: 'settings-only', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'display.terrainReset', section: 'display', label: 'Reset 3D settings', description: 'Restore the 3D display defaults.', synonyms: ['reset'], targetId: 'terrain-reset', targetKind: 'button', mainScreen: 'settings-only', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'display.averageToolbar', section: 'display', label: 'Averaging toolbar control', description: 'Toolbar control for spectrum averaging.', synonyms: ['avg'], targetId: 'spectrum-average-toolbar-btn', targetKind: 'button', mainScreen: 'optional', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'display.peakToolbar', section: 'display', label: 'Peak toolbar control', description: 'Toolbar toggle for peak hold.', synonyms: ['peak'], targetId: 'spectrum-peak-toolbar-btn', targetKind: 'toggle', mainScreen: 'optional', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'display.tunePeakToolbar', section: 'display', label: 'Tune peak toolbar control', description: 'Toolbar action to tune to the strongest signal.', synonyms: ['tune peak'], targetId: 'spectrum-tune-peak-btn', targetKind: 'button', mainScreen: 'optional', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'display.rxMeasure', section: 'display', label: 'RX Measure', description: 'Capture and compare raw RX IQ spectra without changing radio settings.', synonyms: ['rx spectrum', 'noise floor', 'firmware comparison'], targetId: 'operations-tab-rx-measure', targetKind: 'button', mainScreen: 'optional', parityStatus: 'wired' }),
  entry({ id: 'display.wakeLockAction', section: 'display', label: 'Wake lock toggle', description: 'Toggle the screen wake lock from the toolbar.', synonyms: ['stay awake', 'wake'], targetId: 'wake-lock-btn', targetKind: 'toggle', mainScreen: 'optional', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'display.freqLockAction', section: 'display', label: 'Frequency lock toggle', description: 'Toggle the VFO frequency lock from the toolbar.', synonyms: ['lock'], targetId: 'freq-lock-btn', targetKind: 'toggle', mainScreen: 'optional', existingSetupPanel: 'display', parityStatus: 'wired' }),

  // ---- Receive and DSP controls promoted from the gap audit ----
  entry({ id: 'receive.nrLevel', section: 'receive', label: 'Noise reduction level', description: 'Strength of the spectral noise reduction.', synonyms: ['nr level'], targetId: 'setup-dsp-nr-level', targetKind: 'slider', mainScreen: 'optional', existingSetupPanel: 'dsp', parityStatus: 'wired' }),
  entry({ id: 'receive.nr2GainMethod', section: 'receive', label: 'NR2 gain method', description: 'Gain method used by the NR2 algorithm.', synonyms: ['nr2', 'gamma'], targetId: 'setup-dsp-nr2-gain-method', targetKind: 'select', mainScreen: 'settings-only', existingSetupPanel: 'dsp', parityStatus: 'wired' }),
  entry({ id: 'receive.nr2NpeMethod', section: 'receive', label: 'NR2 NPE method', description: 'Noise power estimation method for NR2.', synonyms: ['nr2', 'npe'], targetId: 'setup-dsp-nr2-npe-method', targetKind: 'select', mainScreen: 'settings-only', existingSetupPanel: 'dsp', parityStatus: 'wired' }),
  entry({ id: 'receive.nr2PostFilter', section: 'receive', label: 'NR2 post filter', description: 'Post filter applied after NR2.', synonyms: ['nr2', 'post filter'], targetId: 'setup-dsp-nr2-post-filter', targetKind: 'toggle', mainScreen: 'settings-only', existingSetupPanel: 'dsp', parityStatus: 'wired' }),
  entry({ id: 'receive.anrTaps', section: 'receive', label: 'ANR taps', description: 'Filter length for the automatic noise reduction.', synonyms: ['anr', 'taps'], targetId: 'setup-dsp-anr-taps', targetKind: 'slider', mainScreen: 'settings-only', existingSetupPanel: 'dsp', parityStatus: 'wired' }),
  entry({ id: 'receive.anrDelay', section: 'receive', label: 'ANR delay', description: 'Delay used by the automatic noise reduction.', synonyms: ['anr', 'delay'], targetId: 'setup-dsp-anr-delay', targetKind: 'slider', mainScreen: 'settings-only', existingSetupPanel: 'dsp', parityStatus: 'wired' }),
  entry({ id: 'receive.anrGain', section: 'receive', label: 'ANR gain', description: 'Gain for the automatic noise reduction.', synonyms: ['anr', 'gain'], targetId: 'setup-dsp-anr-gain', targetKind: 'slider', mainScreen: 'settings-only', existingSetupPanel: 'dsp', parityStatus: 'wired' }),
  entry({ id: 'receive.anrLeakage', section: 'receive', label: 'ANR leakage', description: 'Leakage for the automatic noise reduction.', synonyms: ['anr', 'leakage'], targetId: 'setup-dsp-anr-leakage', targetKind: 'slider', mainScreen: 'settings-only', existingSetupPanel: 'dsp', parityStatus: 'wired' }),
  entry({ id: 'receive.anrThetis', section: 'receive', label: 'ANR Thetis defaults', description: 'Load the Thetis ANR defaults.', synonyms: ['anr', 'thetis'], targetId: 'setup-dsp-anr-thetis-btn', targetKind: 'button', mainScreen: 'settings-only', existingSetupPanel: 'dsp', parityStatus: 'wired' }),
  entry({ id: 'receive.anrWide', section: 'receive', label: 'ANR wide setting', description: 'Load the wide ANR setting.', synonyms: ['anr', 'wide'], targetId: 'setup-dsp-anr-wide-btn', targetKind: 'button', mainScreen: 'settings-only', existingSetupPanel: 'dsp', parityStatus: 'wired' }),
  entry({ id: 'receive.anfEnabled', section: 'receive', label: 'ANF enable', description: 'Automatic notch filter on or off.', synonyms: ['anf', 'notch'], targetId: 'setup-dsp-anf-enabled', targetKind: 'toggle', mainScreen: 'optional', existingSetupPanel: 'dsp', parityStatus: 'wired' }),
  entry({ id: 'receive.anfTaps', section: 'receive', label: 'ANF taps', description: 'Filter length for the automatic notch filter.', synonyms: ['anf', 'taps'], targetId: 'setup-dsp-anf-taps', targetKind: 'slider', mainScreen: 'settings-only', existingSetupPanel: 'dsp', parityStatus: 'wired' }),
  entry({ id: 'receive.anfDelay', section: 'receive', label: 'ANF delay', description: 'Delay for the automatic notch filter.', synonyms: ['anf', 'delay'], targetId: 'setup-dsp-anf-delay', targetKind: 'slider', mainScreen: 'settings-only', existingSetupPanel: 'dsp', parityStatus: 'wired' }),
  entry({ id: 'receive.anfGain', section: 'receive', label: 'ANF gain', description: 'Gain for the automatic notch filter.', synonyms: ['anf', 'gain'], targetId: 'setup-dsp-anf-gain', targetKind: 'slider', mainScreen: 'settings-only', existingSetupPanel: 'dsp', parityStatus: 'wired' }),
  entry({ id: 'receive.anfLeakage', section: 'receive', label: 'ANF leakage', description: 'Leakage for the automatic notch filter.', synonyms: ['anf', 'leakage'], targetId: 'setup-dsp-anf-leakage', targetKind: 'slider', mainScreen: 'settings-only', existingSetupPanel: 'dsp', parityStatus: 'wired' }),
  entry({ id: 'receive.anfThetis', section: 'receive', label: 'ANF Thetis defaults', description: 'Load the Thetis ANF defaults.', synonyms: ['anf', 'thetis'], targetId: 'setup-dsp-anf-thetis-btn', targetKind: 'button', mainScreen: 'settings-only', existingSetupPanel: 'dsp', parityStatus: 'wired' }),
  entry({ id: 'receive.anfSharp', section: 'receive', label: 'ANF sharp setting', description: 'Load the sharp ANF setting.', synonyms: ['anf', 'sharp'], targetId: 'setup-dsp-anf-sharp-btn', targetKind: 'button', mainScreen: 'settings-only', existingSetupPanel: 'dsp', parityStatus: 'wired' }),
  entry({ id: 'receive.rxEq', section: 'receive', label: 'RX equaliser', description: 'Receive audio equaliser bands.', synonyms: ['eq', 'rx eq'], targetId: 'rx-eq-enable-btn', targetKind: 'toggle', mainScreen: 'settings-only', existingSetupPanel: 'dsp', parityStatus: 'wired' }),
  entry({ id: 'receive.nrLevelQuick', section: 'receive', label: 'Noise reduction level (panel)', description: 'Noise reduction level on the receive panel.', synonyms: ['nr'], targetId: 'rx-nr-level', targetKind: 'slider', mainScreen: 'optional', existingSetupPanel: 'dsp', parityStatus: 'wired' }),
  entry({ id: 'receive.nbThresholdQuick', section: 'receive', label: 'Noise blanker threshold (panel)', description: 'Noise blanker threshold on the receive panel.', synonyms: ['nb'], targetId: 'rx-nb-threshold', targetKind: 'slider', mainScreen: 'optional', existingSetupPanel: 'dsp', parityStatus: 'wired' }),
  entry({ id: 'receive.wfmMode', section: 'receive', label: 'WFM mode', description: 'Switch the receiver into wide FM.', synonyms: ['wfm', 'fm'], targetId: 'wfm-mode-btn', targetKind: 'button', mainScreen: 'always', existingSetupPanel: 'dsp', parityStatus: 'wired' }),

  // ---- Transmit, radio and audio controls promoted from the gap audit ----
  entry({ id: 'transmit.twoToneEnable', section: 'transmit', label: 'Two-tone generator', description: 'Enable the two-tone transmit test signal.', synonyms: ['two tone'], targetId: 'two-tone-btn', targetKind: 'toggle', mainScreen: 'settings-only', existingSetupPanel: 'tx', parityStatus: 'wired' }),
  entry({ id: 'transmit.txSetup', section: 'transmit', label: 'TX setup disclosure', description: 'The reveal that holds the transmit gate, expander, processor, CESSB and filter controls.', synonyms: ['tx setup', 'advanced tx'], targetId: 'tx-advanced-card', targetKind: 'overlay', mainScreen: 'settings-only', existingSetupPanel: 'tx', parityStatus: 'wired' }),
  entry({ id: 'transmit.appBarBadge', section: 'transmit', label: 'TX state badge', description: 'Always-visible transmit state badge in the app bar; never collapsed at any width.', synonyms: ['tx badge', 'tx state', 'on air'], targetId: 'app-tx-state-badge', targetKind: 'indicator', mainScreen: 'always', safetyPinned: true, parityStatus: 'wired', domTextToken: 'TX' }),
  entry({ id: 'shell.onAirBar', section: 'transmit', label: 'On-air bar', description: 'Danger bar across the top of the viewport while transmitting, visible at every width.', synonyms: ['on air', 'transmitting'], targetId: 'tx-on-air-bar', targetKind: 'indicator', mainScreen: 'always', safetyPinned: true, parityStatus: 'wired', domTextToken: 'TX' }),
  entry({ id: 'transmit.stateAnnouncement', section: 'transmit', label: 'Transmit state announcement', description: 'Screen-reader announcement region for transmit state changes; an announcement, not a control, so it is never pinned or toggled.', synonyms: ['aria live', 'announcement'], targetId: 'tx-state-live', targetKind: 'indicator', mainScreen: 'settings-only', parityStatus: 'wired' }),
  entry({ id: 'shell.mobileDock', section: 'interface', label: 'Phone dock', description: 'Phone context dock for Radio, RX, TX, DSP and more; navigation, not a setting.', synonyms: ['dock', 'phone dock'], targetId: 'mobile-control-dock', targetKind: 'overlay', mainScreen: 'always', parityStatus: 'wired' }),
  entry({ id: 'transmit.cfcEnable', section: 'transmit', label: 'CFC enable', description: 'Continuous frequency compression on or off.', synonyms: ['cfc'], targetId: 'cfc-enable-btn', targetKind: 'toggle', mainScreen: 'settings-only', existingSetupPanel: 'tx', parityStatus: 'wired' }),
  entry({ id: 'transmit.cfcPrecomp', section: 'transmit', label: 'CFC pre-compensation', description: 'Pre-compensation level for the CFC bands.', synonyms: ['cfc', 'precomp'], targetId: 'cfc-precomp', targetKind: 'slider', mainScreen: 'settings-only', existingSetupPanel: 'tx', parityStatus: 'wired' }),
  entry({ id: 'transmit.timeoutSeconds', section: 'transmit', label: 'TX timeout seconds', description: 'Maximum transmit duration before it is stopped.', synonyms: ['timeout'], targetId: 'setup-tx-timeout-seconds', targetKind: 'slider', mainScreen: 'settings-only', existingSetupPanel: 'tx', parityStatus: 'wired' }),
  entry({ id: 'transmit.phaseRotatorAuto', section: 'transmit', label: 'Phase rotator auto', description: 'Track the phase rotator corner automatically.', synonyms: ['phase rotator'], targetId: 'setup-tx-phase-rotator-auto', targetKind: 'toggle', mainScreen: 'settings-only', existingSetupPanel: 'tx', parityStatus: 'wired' }),
  entry({ id: 'transmit.phaseRotatorCorner', section: 'transmit', label: 'Phase rotator corner', description: 'Phase rotator corner frequency.', synonyms: ['phase rotator'], targetId: 'setup-tx-phase-rotator-corner', targetKind: 'slider', mainScreen: 'settings-only', existingSetupPanel: 'tx', parityStatus: 'wired' }),
  entry({ id: 'transmit.puresignalAutoAttenuate', section: 'transmit', label: 'PureSignal auto attenuation', description: 'Let PureSignal choose the feedback attenuation.', synonyms: ['puresignal'], targetId: 'setup-tx-puresignal-auto-attenuate', targetKind: 'toggle', mainScreen: 'settings-only', existingSetupPanel: 'tx', parityStatus: 'wired' }),
  entry({ id: 'transmit.puresignalAttenuation', section: 'transmit', label: 'PureSignal attenuation', description: 'Manual PureSignal feedback attenuation.', synonyms: ['puresignal'], targetId: 'setup-tx-puresignal-attenuation', targetKind: 'slider', mainScreen: 'settings-only', existingSetupPanel: 'tx', parityStatus: 'wired' }),
  entry({ id: 'transmit.puresignalReset', section: 'transmit', label: 'Reset PureSignal', description: 'Clear the PureSignal calibration.', synonyms: ['puresignal', 'reset'], targetId: 'setup-tx-puresignal-reset', targetKind: 'button', mainScreen: 'settings-only', existingSetupPanel: 'tx', parityStatus: 'wired' }),
  entry({ id: 'transmit.dexpThreshold', section: 'transmit', label: 'Expander threshold', description: 'Downward expander threshold.', synonyms: ['dexp'], targetId: 'tx-dexp-threshold', targetKind: 'slider', mainScreen: 'settings-only', existingSetupPanel: 'tx', parityStatus: 'wired' }),
  entry({ id: 'transmit.dexpExpansion', section: 'transmit', label: 'Expander ratio', description: 'Downward expander expansion ratio.', synonyms: ['dexp'], targetId: 'tx-dexp-expansion', targetKind: 'slider', mainScreen: 'settings-only', existingSetupPanel: 'tx', parityStatus: 'wired' }),
  entry({ id: 'transmit.speechProcessorGain', section: 'transmit', label: 'Speech processor gain', description: 'Gain applied by the speech processor.', synonyms: ['speech processor'], targetId: 'tx-speech-processor-gain', targetKind: 'slider', mainScreen: 'settings-only', existingSetupPanel: 'tx', parityStatus: 'wired' }),
  entry({ id: 'transmit.noiseGateThreshold', section: 'transmit', label: 'TX noise gate threshold', description: 'Level below which transmit audio is gated.', synonyms: ['noise gate'], targetId: 'tx-noise-gate-threshold', targetKind: 'slider', mainScreen: 'settings-only', existingSetupPanel: 'tx', parityStatus: 'wired' }),
  entry({ id: 'transmit.voodoo38k', section: 'transmit', label: 'Voodoo 38k', description: 'Apply the 38 kHz transmit offset correction.', synonyms: ['voodoo'], targetId: 'apply-voodoo-38k-btn', targetKind: 'button', mainScreen: 'settings-only', existingSetupPanel: 'tx', parityStatus: 'wired' }),
  entry({ id: 'transmit.satpKey', section: 'transmit', label: 'SATP pairing key', description: 'Native sender pairing key.', synonyms: ['satp', 'key'], targetId: 'satp-key', targetKind: 'readout', mainScreen: 'settings-only', existingSetupPanel: 'tx', parityStatus: 'wired' }),
  entry({ id: 'transmit.satpCopyKey', section: 'transmit', label: 'Copy SATP key', description: 'Copy the pairing key to the clipboard.', synonyms: ['satp', 'copy'], targetId: 'satp-copy-key', targetKind: 'button', mainScreen: 'settings-only', existingSetupPanel: 'tx', parityStatus: 'wired' }),
  entry({ id: 'transmit.satpHideKey', section: 'transmit', label: 'Hide SATP key', description: 'Hide the pairing key on screen.', synonyms: ['satp', 'hide'], targetId: 'satp-hide-key', targetKind: 'toggle', mainScreen: 'settings-only', existingSetupPanel: 'tx', parityStatus: 'wired' }),
  entry({ id: 'transmit.txToolSelect', section: 'transmit', label: 'TX tool select', description: 'Choose which transmit tool is shown.', synonyms: ['tx tool'], targetId: 'tx-tool-select', targetKind: 'select', mainScreen: 'settings-only', existingSetupPanel: 'tx', parityStatus: 'wired' }),
  entry({ id: 'transmit.txToolOpen', section: 'transmit', label: 'Open TX tool', description: 'Open the selected transmit tool.', synonyms: ['tx tool'], targetId: 'tx-tool-open-btn', targetKind: 'button', mainScreen: 'settings-only', existingSetupPanel: 'tx', parityStatus: 'wired' }),
  entry({ id: 'meter.txMeterMode', section: 'meter', label: 'TX meter mode', description: 'Which meter is shown while transmitting.', synonyms: ['meter', 'tx meter'], targetId: 'tx-meter-mode', targetKind: 'select', mainScreen: 'optional', existingSetupPanel: 'tx', parityStatus: 'wired' }),
  entry({ id: 'meter.peakButton', section: 'meter', label: 'Meter peak hold', description: 'Hold the meter peak value.', synonyms: ['peak'], targetId: 'instrument-meter-peak-btn', targetKind: 'toggle', mainScreen: 'optional', existingSetupPanel: 'display', parityStatus: 'wired' }),
  entry({ id: 'radio.sampleRate', section: 'radio', label: 'Sample rate', description: 'IQ sample rate requested from the radio.', synonyms: ['sample rate'], targetId: 'sample-rate', targetKind: 'select', mainScreen: 'optional', existingSetupPanel: 'advanced', parityStatus: 'wired' }),
  entry({ id: 'radio.rxAdc', section: 'radio', label: 'RX ADC', description: 'Receive ADC selection.', synonyms: ['adc'], targetId: 'rx-adc', targetKind: 'select', mainScreen: 'optional', existingSetupPanel: 'advanced', parityStatus: 'wired' }),
  entry({ id: 'radio.streamMode', section: 'radio', label: 'Stream mode', description: 'LAN or WAN stream mode for the display.', synonyms: ['stream mode', 'wan', 'lan'], targetId: 'setup-stream-mode', targetKind: 'select', mainScreen: 'optional', existingSetupPanel: 'network', parityStatus: 'wired' }),
  entry({ id: 'radio.profileSelect', section: 'radio', label: 'Profile select', description: 'Choose a saved remote settings profile.', synonyms: ['profile'], targetId: 'setup-profile-select', targetKind: 'select', mainScreen: 'settings-only', existingSetupPanel: 'profiles', parityStatus: 'wired' }),
  entry({ id: 'radio.profileLoad', section: 'radio', label: 'Load profile', description: 'Load the selected profile.', synonyms: ['profile', 'load'], targetId: 'setup-profile-load-btn', targetKind: 'button', mainScreen: 'settings-only', existingSetupPanel: 'profiles', parityStatus: 'wired' }),
  entry({ id: 'radio.profileSave', section: 'radio', label: 'Save profile', description: 'Save the current settings to the selected profile.', synonyms: ['profile', 'save'], targetId: 'setup-profile-save-btn', targetKind: 'button', mainScreen: 'settings-only', existingSetupPanel: 'profiles', parityStatus: 'wired' }),
  entry({ id: 'radio.profileSaveAs', section: 'radio', label: 'Save profile as', description: 'Save the current settings as a new profile.', synonyms: ['profile', 'save as'], targetId: 'setup-profile-save-as-btn', targetKind: 'button', mainScreen: 'settings-only', existingSetupPanel: 'profiles', parityStatus: 'wired' }),
  entry({ id: 'radio.profileDelete', section: 'radio', label: 'Delete profile', description: 'Delete a saved profile; the only native confirmation in the app.', synonyms: ['profile', 'delete'], targetId: 'setup-profile-delete-btn', targetKind: 'button', mainScreen: 'settings-only', existingSetupPanel: 'profiles', parityStatus: 'wired' }),
  entry({ id: 'radio.startupProfileSelect', section: 'radio', label: 'Startup profile', description: 'Profile applied when the console connects.', synonyms: ['startup', 'profile'], targetId: 'setup-startup-profile-select', targetKind: 'select', mainScreen: 'settings-only', existingSetupPanel: 'profiles', parityStatus: 'wired' }),
  entry({ id: 'radio.startupProfileApply', section: 'radio', label: 'Apply startup profile now', description: 'Apply the startup profile immediately.', synonyms: ['startup', 'apply'], targetId: 'setup-startup-apply-btn', targetKind: 'button', mainScreen: 'settings-only', existingSetupPanel: 'profiles', parityStatus: 'wired' }),
  entry({ id: 'radio.startupProfileClear', section: 'radio', label: 'Clear startup profile', description: 'Stop applying a startup profile.', synonyms: ['startup', 'clear'], targetId: 'setup-startup-clear-btn', targetKind: 'button', mainScreen: 'settings-only', existingSetupPanel: 'profiles', parityStatus: 'wired' }),
  entry({ id: 'audio.inputSelect', section: 'audio', label: 'Microphone device', description: 'Browser microphone device for transmit audio.', synonyms: ['input', 'mic'], targetId: 'setup-audio-input-select', targetKind: 'select', mainScreen: 'settings-only', existingSetupPanel: 'audio', parityStatus: 'wired' }),
  entry({ id: 'audio.outputSelect', section: 'audio', label: 'Output device', description: 'Browser output device for receive audio.', synonyms: ['output', 'speaker'], targetId: 'setup-audio-output-select', targetKind: 'select', mainScreen: 'settings-only', existingSetupPanel: 'audio', parityStatus: 'wired' }),
  entry({ id: 'audio.refreshDevices', section: 'audio', label: 'Refresh audio devices', description: 'Re-enumerate the available audio devices.', synonyms: ['devices', 'refresh'], targetId: 'setup-audio-refresh-devices-btn', targetKind: 'button', mainScreen: 'settings-only', existingSetupPanel: 'audio', parityStatus: 'wired' }),
  entry({ id: 'display.terrainTraditionalSettings', section: 'display', label: 'Traditional waterfall settings', description: 'Open the traditional waterfall settings.', synonyms: ['waterfall', 'settings'], targetId: 'terrain-traditional-settings', targetKind: 'button', mainScreen: 'settings-only', existingSetupPanel: 'display', parityStatus: 'wired' }),
];

export const SETTINGS_REGISTRY_BY_ID: ReadonlyMap<string, SettingsEntry> = new Map(
  SETTINGS_REGISTRY.map((item) => [item.id, item]),
);

export const SAFETY_PINNED_IDS: readonly string[] = ['radio.vfoA', 'transmit.appBarBadge', 'transmit.arm', 'transmit.ptt', 'shell.onAirBar', 'shell.settings'];
